<?php

return [
    'business' => [
        'name' => 'B-Brillant',
        'founded' => 2008,
        'address' => 'Rruga Gjergj Fishta, 14000 Lipjan, Kosovë',
        'phones' => ['+383 44 996 926', '+383 44 960 661'],
        'whatsapp' => '+383 44 960 661',
        'languages' => ['shqip', 'English', 'srpski'],
        'payment' => 'Porosia online aktualisht paguhet kesh në dorëzim.',
        'delivery' => 'B-Brillant bën dërgesa në Kosovë. Afati dhe kostoja përfundimtare konfirmohen gjatë porosisë ose nga ekipi.',
        'services' => [
            'Këshillim për zgjedhjen dhe kombinimin e produkteve për shtëpi.',
            'Këshillim për matje dhe montim të perdeve sipas mundësisë; detajet konfirmohen nga ekipi.',
            'Porosi online, shportë, checkout dhe gjurmim me kod porosie në website.',
        ],
    ],

    // Rendi ka rëndësi: kategoritë specifike duhet të jenë para atyre të përgjithshme.
    'categories' => [
        'bath_rugs' => [
            'label' => 'Tepiha për banjo',
            'action_label' => 'Shiko tepihat e banjos',
            'category' => 'tepihebanjo',
            'subcategory' => null,
            'route' => 'products.tepihebanjo',
            'aliases' => ['tepih banjo', 'tepiha banjo', 'tapet banjo', 'banjoje', 'bath rug', 'bath mat', 'kupatilski tepih'],
            'generic' => ['tepih', 'tepiha', 'tapet', 'banjo', 'banjoje', 'bath', 'rug', 'mat', 'kupatilski'],
        ],
        'side_curtains' => [
            'label' => 'Perde anësore',
            'action_label' => 'Shiko perdet anësore',
            'category' => 'perde',
            'subcategory' => 'anesore',
            'route' => 'products.anesore',
            'aliases' => ['perde anesore', 'perde anësore', 'side curtain', 'side curtains', 'bocne zavese', 'bočne zavese'],
            'generic' => ['perde', 'anesore', 'anësore', 'side', 'curtain', 'curtains', 'bocne', 'bočne', 'zavese'],
        ],
        'day_curtains' => [
            'label' => 'Perde ditore',
            'action_label' => 'Shiko perdet ditore',
            'category' => 'perde',
            'subcategory' => 'ditore',
            'route' => 'products.perdeDitore',
            'aliases' => ['perde ditore', 'day curtain', 'day curtains', 'dnevne zavese'],
            'generic' => ['perde', 'ditore', 'day', 'curtain', 'curtains', 'dnevne', 'zavese'],
        ],
        'plush_fur' => [
            'label' => 'Lëkurë pelushi',
            'action_label' => 'Shiko lëkurët e pelushit',
            'category' => 'posteqia',
            'subcategory' => null,
            'route' => 'products.posteqia',
            'aliases' => ['posteqia', 'posteqe', 'lekure pelushi', 'lëkurë pelushi', 'pelush', 'plush fur', 'plisano krzno'],
            'generic' => ['posteqia', 'posteqe', 'lekure', 'lëkurë', 'pelushi', 'pelush', 'plush', 'fur', 'plisano', 'krzno'],
        ],
        'rugs' => [
            'label' => 'Tepiha',
            'action_label' => 'Shiko tepihat',
            'category' => 'tepiha',
            'subcategory' => null,
            'route' => 'products.tepiha',
            'aliases' => ['tepiha', 'tepih', 'tapet', 'hali', 'halli', 'rug', 'rugs', 'carpet', 'tepisi'],
            'generic' => ['tepiha', 'tepih', 'tapet', 'rug', 'rugs', 'tepisi'],
        ],
        'curtains' => [
            'label' => 'Perde',
            'action_label' => 'Shiko perdet',
            'category' => 'perde',
            'subcategory' => null,
            'route' => 'products.perde',
            'aliases' => ['perde', 'dritare', 'curtain', 'curtains', 'zavese'],
            'generic' => ['perde', 'dritare', 'curtain', 'curtains', 'zavese'],
        ],
        'bedsheets' => [
            'label' => 'Set çarçafësh',
            'action_label' => 'Shiko setet e çarçafëve',
            'category' => 'postava',
            'subcategory' => null,
            'route' => 'products.postava',
            'aliases' => ['postava', 'carcaf', 'çarçaf', 'qarqaf', 'qaraqaf', 'bedsheet', 'bed sheet', 'posteljina'],
            'generic' => ['postava', 'carcaf', 'çarçaf', 'qarqaf', 'qaraqaf', 'set', 'bedsheet', 'bed', 'sheet', 'posteljina'],
        ],
        'blankets' => [
            'label' => 'Batanije',
            'action_label' => 'Shiko batanijet',
            'category' => 'batanije',
            'subcategory' => null,
            'route' => 'products.batanije',
            'aliases' => ['batanije', 'qebe', 'blanket', 'blankets', 'cebe', 'ćebe'],
            'generic' => ['batanije', 'qebe', 'blanket', 'blankets', 'cebe', 'ćebe'],
        ],
        'covers' => [
            'label' => 'Mbulesa',
            'action_label' => 'Shiko mbulesat',
            'category' => 'mbulesa',
            'subcategory' => null,
            'route' => 'products.mbulesa',
            'aliases' => ['mbulesa', 'mbulese', 'mbulesë', 'sofa cover', 'bed cover', 'prekrivac', 'prekrivač'],
            'generic' => ['mbulesa', 'mbulese', 'mbulesë', 'cover', 'sofa', 'bed', 'prekrivac', 'prekrivač'],
        ],
        'pillows' => [
            'label' => 'Jastëkë dekorues',
            'action_label' => 'Shiko jastëkët',
            'category' => 'jastekdekorues',
            'subcategory' => null,
            'route' => 'products.jastekdekorues',
            'aliases' => ['jastek', 'jastëk', 'jastak', 'dekorues', 'decorative pillow', 'dekorativni jastuk'],
            'generic' => ['jastek', 'jastëk', 'jastak', 'dekorues', 'decorative', 'pillow', 'dekorativni', 'jastuk'],
        ],
        'rails' => [
            'label' => 'Garnishte',
            'action_label' => 'Shiko garnishtet',
            'category' => 'garnishte',
            'subcategory' => null,
            'route' => 'products.garnishte',
            'aliases' => ['garnishte', 'garnish', 'karnish', 'karnise', 'curtain rail', 'curtain rod', 'garnisne'],
            'generic' => ['garnishte', 'garnish', 'karnish', 'karnise', 'curtain', 'rail', 'rod', 'garnisne'],
        ],
    ],

    'pages' => [
        ['label' => 'Ballina', 'route' => 'home', 'keywords' => ['ballina', 'home']],
        ['label' => 'Të gjitha produktet', 'route' => 'products.index', 'keywords' => ['produkte', 'produktet', 'catalog', 'katalog', 'shop', 'qka keni', 'cka keni', 'çka keni', 'qfare shisni', 'çfarë shisni']],
        ['label' => 'Shporta', 'route' => 'cart.index', 'keywords' => ['shporta', 'cart']],
        ['label' => 'Përfundo porosinë', 'route' => 'checkout.index', 'keywords' => ['checkout', 'blej', 'porosit', 'porosi online']],
        ['label' => 'Gjurmo porosinë', 'route' => 'track.form', 'keywords' => ['gjurmo', 'tracking', 'kodi porosise', 'status porosie']],
        ['label' => 'Kontakti dhe adresa', 'route' => 'contact', 'keywords' => ['kontakt', 'telefoni', 'whatsapp', 'adresa', 'lokacioni', 'lokacion', 'ku jeni', 'ku gjendeni', 'ku gjendet', 'ku gjindeni', 'ku gjindet', 'ku ndodheni']],
        ['label' => 'Rreth B-Brillant', 'route' => 'about', 'keywords' => ['rreth', 'about', 'historia', 'kush jeni']],
        ['label' => 'Hyr në llogari', 'route' => 'login', 'keywords' => ['login', 'kycu', 'kyçu', 'llogaria']],
    ],

    'color_synonyms' => [
        ['gri', 'hir', 'hiri', 'hirte', 'hirtë', 'hirta', 'grey', 'gray', 'siva', 'sivo'],
        ['bardh', 'bardhe', 'bardhë', 'bardha', 'white', 'bela', 'bijela'],
        ['krem', 'cream', 'kremova'],
        ['kafe', 'brown', 'braon', 'smedja', 'smeđa'],
        ['roz', 'roze', 'rozë', 'pink', 'roza'],
        ['kuq', 'kuqe', 'red', 'crvena'],
        ['zez', 'zeze', 'zezë', 'zi', 'black', 'crna'],
        ['bezh', 'bezhe', 'bezhë', 'beige', 'bez', 'bež'],
        ['kalter', 'kaltër', 'blu', 'blue', 'plava'],
        ['gjelber', 'gjelbër', 'green', 'zelena'],
    ],

    'stop_words' => [
        'pershendetje', 'përshëndetje', 'hello', 'hi', 'tung', 'keni', 'kena', 'kemi', 'kam', 'dua', 'du', 'duhet',
        'nje', 'një', 'naj', 'cilat', 'cilin', 'cila', 'qfare', 'çfare', 'çfarë', 'mund', 'me', 'per', 'për',
        'dhe', 'edhe', 'apo', 'ose', 'nga', 'tek', 'te', 'ne', 'në', 'ka', 'ju', 'jam', 'po', 'a', 'e', 'i', 'o', 'mi', 'ma',
        'qfar', 'çfar', 'cfar', 'ngjyre', 'ngjyrë', 'ngjyra', 'ngjyrat', 'madhesi', 'madhësi', 'masa', 'masat',
        'dimension', 'dimensione', 'permasa', 'përmasa', 'permasat', 'përmasat', 'stok', 'stock', 'disponueshem', 'disponueshëm', 'disponueshme', 'available',
        'vetem', 'vetëm', 'only', 'cmim', 'çmim', 'cmimet', 'çmimet', 'kushton', 'sa', 'jon', 'jane', 'janë',
        'meter', 'metra', 'metre', 'meters',
        'person', 'persona', 'veta', 'dy', 'ddy', 'dopio', 'double', 'cift', 'çift', 'matrimonial', 'teke', 'single',
        'qit', 'qita', 'qito', 'qikjo', 'qiky', 'qika', 'kete', 'këtë', 'ket', 'kët', 'ate', 'atë', 'paren', 'parin', 'tparen', 'dyten', 'dytin', 'treten', 'tretin',
        'qka', 'cka', 'çka', 'produkt', 'produkte', 'produktet', 'katalog', 'shop', 'shisni', 'gjej', 'gjeni', 'kerkoj', 'kërkoj', 'trego', 'disa',
        'gjithe', 'gjithë', 'krejt', 'secili', 'secila', 'seciles', 'çdo', 'cdo', 'all', 'every',
        'model', 'modele', 'modelet', 'cop', 'cope', 'copë', 'copa', 'osht', 'eshte', 'është', 'jepmi', 'qitmi',
        'show', 'have', 'with', 'for', 'the', 'and', 'please', 'imate', 'treba', 'koji', 'koja', 'molim',
    ],

    // Këto ndikojnë renditjen, por mungesa e tyre nuk e përjashton produktin.
    'soft_preferences' => [
        'modern', 'moderne', 'klasik', 'klasike', 'premium', 'bute', 'butë', 'ngrohte', 'ngrohtë',
        'sallon', 'dhom', 'korridor', 'kuzhin', 'zyre', 'zyrë', 'familje', 'ri', 'reja', 'latest', 'new',
        'lire', 'lirë', 'cheap', 'budget', 'shtrenjte', 'shtrenjtë', 'expensive', 'tjeter', 'tjetër', 'alternative', 'another',
    ],
];
